- name: Create user
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Add user
      tags: [ users ]
      loop: "{{ users }}"
      loop_control:
        label: "{{ item.user }}"
      user:
        name: "{{ item.user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        password: "{{ item.password_hash }}"

    - name: Add authorized key
      tags: [ users ]
      loop: "{{ users | subelements('pubkeys') }}"
      loop_control:
        label: "{{ item.0.user }}"
      authorized_key:
        user: "{{ item.0.user }}"
        state: present
        key: "{{ item.1 }}"

    - name: Upgrade packages
      apt:
        update_cache: yes
        upgrade: "yes"

    - name: Prepare host for user switching
      apt:
        name: acl
        state: present
